<a href="https://colab.research.google.com/github/athirasureshev-lab/Accidental_Drug_Related_Death/blob/main/Python_Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.** Data Loading and Initial Overview**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Accidental_Drug_Related_Death.xlsx to Accidental_Drug_Related_Death.xlsx

In [5]:
import pandas as pd

df = pd.read_excel("Accidental_Drug_Related_Death.xlsx")

df.head()
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1546 entries, 0 to 1545
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Date of death                  1546 non-null   datetime64[ns]
 1   Age                            1546 non-null   int64
 2   Sex                            1545 non-null   object
 3   Race                           1528 non-null   object
 4   Residence City                 1447 non-null   object
 5   Residence County               1438 non-null   object
 6   Residence State                1443 non-null   object
 7   Injury City                    1515 non-null   object
 8   Injury County                  1487 non-null   object
 9   Injury State                   1468 non-null   object
 10  Injury Place                   1426 non-null   object
 11  Description of Injury          1539 non-null   object
 12  Location                       599 non-null    object
 13  Location if Other              138 non-null    object
 14  Cause of Death                 1546 non-null   object
 15  Manner of Death                1546 non-null   object
 16  Other Significant Conditions   221 non-null    object
 17  Heroin                         130 non-null    object
 18  Cocaine                        847 non-null    object
 19  Fentanyl                       1296 non-null   object
 20  Fentanyl Analogue              116 non-null    object
 21  Oxycodone                      84 non-null     object
 22  Oxymorphone                    12 non-null     object
 23  Ethanol                        358 non-null    object
 24  Hydrocodone                    6 non-null      object
 25  Benzodiazepine                 269 non-null    object
 26  Methadone                      142 non-null    object
 27  Amphet                         82 non-null     object
 28  Tramad                         23 non-null     object
 29  Hydromorphone                  8 non-null      object
 30  Morphine (Not Heroin)          4 non-null      object
 31  Xylazine                       412 non-null    object
 32  Gabapentin                     151 non-null    object
 33  Opiate NOS                     4 non-null      object
 34  Heroin/Morph/Codeine           137 non-null    object
 35  Other Opioid                   90 non-null     object
 36  Any Opioid                     1445 non-null   object
dtypes: datetime64[ns](1), int64(1), object(35)
memory usage: 447.0+ KB

                       Date of death          Age
count                           1546  1546.000000
mean   2023-04-25 08:01:33.143596544    47.911384
min              2022-01-01 00:00:00    16.000000
25%              2022-08-03 00:00:00    37.000000
50%              2023-04-01 12:00:00    49.000000
75%              2024-01-02 00:00:00    58.000000
max              2024-12-12 00:00:00    78.000000
std                              NaN    12.681022


## 1.Number of Rows and Columns

In [28]:
df.shape

(1546, 37)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1546 entries, 0 to 1545
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date_of_death                 1546 non-null   datetime64[ns]
 1   Age                           1546 non-null   int64
 2   Sex                           1545 non-null   object
 3   Race                          1528 non-null   object
 4   Residence_City                1447 non-null   object
 5   Residence_County              1438 non-null   object
 6   Residence_State               1443 non-null   object
 7   Injury_City                   1515 non-null   object
 8   Injury_County                 1487 non-null   object
 9   Injury_State                  1468 non-null   object
 10  Injury_Place                  1426 non-null   object
 11  Description_of_Injury         1539 non-null   object
 12  Location                      599 non-null    object
 13  Location_if_Other             138 non-null    object
 14  Cause_of_Death                1546 non-null   object
 15  Manner_of_Death               1546 non-null   object
 16  Other_Significant_Conditions  221 non-null    object
 17  Heroin                        130 non-null    object
 18  Cocaine                       847 non-null    object
 19  Fentanyl                      1296 non-null   object
 20  Fentanyl_Analogue             116 non-null    object
 21  Oxycodone                     84 non-null     object
 22  Oxymorphone                   12 non-null     object
 23  Ethanol                       358 non-null    object
 24  Hydrocodone                   6 non-null      object
 25  Benzodiazepine                269 non-null    object
 26  Methadone                     142 non-null    object
 27  Amphet                        82 non-null     object
 28  Tramad                        23 non-null     object
 29  Hydromorphone                 8 non-null      object
 30  Morphine_(Not_Heroin)         4 non-null      object
 31  Xylazine                      412 non-null    object
 32  Gabapentin                    151 non-null    object
 33  Opiate_NOS                    4 non-null      object
 34  Heroin/Morph/Codeine          137 non-null    object
 35  Other_Opioid                  90 non-null     object
 36  Any_Opioid                    1445 non-null   object
dtypes: datetime64[ns](1), int64(1), object(35)
memory usage: 447.0+ KB

Initial Observations

In [30]:
df.head()

,Date_of_death,Age,Sex,Race,Residence_City,Residence_County,Residence_State,Injury_City,Injury_County,Injury_State,...,Amphet,Tramad,Hydromorphone,Morphine_(Not_Heroin),Xylazine,Gabapentin,Opiate_NOS,Heroin/Morph/Codeine,Other_Opioid,Any_Opioid
0,2023-02-01,65,Male,White,BRIDGEPORT,FAIRFIELD,CT,BRIDGEPORT,FAIRFIELD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1,2023-04-02,34,Male,White,NaN,NaN,NaN,NEW HAVEN,NEW HAVEN,CT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
2,2022-01-03,24,Male,White,HARTFORD,HARTFORD,CT,HARTFORD,HARTFORD,CT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
3,2023-06-03,77,Male,White,BRISTOL,HARTFORD,CT,BRISTOL,HARTFORD,CT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
4,2023-06-07,53,Male,White,NEW HAVEN,NEW HAVEN,CT,NEW HAVEN,NEW HAVEN,CT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y

In [31]:
df.describe()

                       Date_of_death          Age
count                           1546  1546.000000
mean   2023-04-25 08:01:33.143596544    47.911384
min              2022-01-01 00:00:00    16.000000
25%              2022-08-03 00:00:00    37.000000
50%              2023-04-01 12:00:00    49.000000
75%              2024-01-02 00:00:00    58.000000
max              2024-12-12 00:00:00    78.000000
std                              NaN    12.681022

# 2. Data Pre-processing
### Check Missing Values

In [60]:
df[drug_columns].isnull().sum()

Heroin       0
Cocaine      0
Fentanyl     0
Methadone    0
dtype: int64

In [61]:
df[drug_columns].head()

  Heroin  Cocaine  Fentanyl Methadone
0      0  Cocaine  Fentanyl         0
1      0  Cocaine  Fentanyl         0
2      0        0  Fentanyl         0
3      0        0  Fentanyl         0
4      0        0  Fentanyl         0

In [62]:
print("Missing values before:")
print(df[drug_columns].isnull().sum())

df[drug_columns] = df[drug_columns].fillna(0)

print("\nMissing values after:")
print(df[drug_columns].isnull().sum())

Missing values before:
Heroin       0
Cocaine      0
Fentanyl     0
Methadone    0
dtype: int64

Missing values after:
Heroin       0
Cocaine      0
Fentanyl     0
Methadone    0
dtype: int64

## Replace missing values in drug column

In [82]:
drug_columns = ['Heroin','Cocaine','Fentanyl','Methadone','Any_Opioid']

df[drug_columns] = df[drug_columns].fillna(0)

## Remove Duplicate Records

In [34]:
# Check number of duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Remove duplicates
df.drop_duplicates(inplace=True)

# Confirm removal
print("Rows after removing duplicates:", df.shape)

Duplicate rows: 0
Rows after removing duplicates: (1546, 37)

## Correct Data Types

Convert date column:

In [37]:
print(df.columns)

Index(['Date_of_death', 'Age', 'Sex', 'Race', 'Residence_City',
       'Residence_County', 'Residence_State', 'Injury_City', 'Injury_County',
       'Injury_State', 'Injury_Place', 'Description_of_Injury', 'Location',
       'Location_if_Other', 'Cause_of_Death', 'Manner_of_Death',
       'Other_Significant_Conditions', 'Heroin', 'Cocaine', 'Fentanyl',
       'Fentanyl_Analogue', 'Oxycodone', 'Oxymorphone', 'Ethanol',
       'Hydrocodone', 'Benzodiazepine', 'Methadone', 'Amphet', 'Tramad',
       'Hydromorphone', 'Morphine_(Not_Heroin)', 'Xylazine', 'Gabapentin',
       'Opiate_NOS', 'Heroin/Morph/Codeine', 'Other_Opioid', 'Any_Opioid'],
      dtype='object')

In [39]:
print(df.columns.tolist())

['Date_of_death', 'Age', 'Sex', 'Race', 'Residence_City', 'Residence_County', 'Residence_State', 'Injury_City', 'Injury_County', 'Injury_State', 'Injury_Place', 'Description_of_Injury', 'Location', 'Location_if_Other', 'Cause_of_Death', 'Manner_of_Death', 'Other_Significant_Conditions', 'Heroin', 'Cocaine', 'Fentanyl', 'Fentanyl_Analogue', 'Oxycodone', 'Oxymorphone', 'Ethanol', 'Hydrocodone', 'Benzodiazepine', 'Methadone', 'Amphet', 'Tramad', 'Hydromorphone', 'Morphine_(Not_Heroin)', 'Xylazine', 'Gabapentin', 'Opiate_NOS', 'Heroin/Morph/Codeine', 'Other_Opioid', 'Any_Opioid']

In [40]:
df.columns = df.columns.str.strip().str.replace(" ", "_")
print(df.columns)

Index(['Date_of_death', 'Age', 'Sex', 'Race', 'Residence_City',
       'Residence_County', 'Residence_State', 'Injury_City', 'Injury_County',
       'Injury_State', 'Injury_Place', 'Description_of_Injury', 'Location',
       'Location_if_Other', 'Cause_of_Death', 'Manner_of_Death',
       'Other_Significant_Conditions', 'Heroin', 'Cocaine', 'Fentanyl',
       'Fentanyl_Analogue', 'Oxycodone', 'Oxymorphone', 'Ethanol',
       'Hydrocodone', 'Benzodiazepine', 'Methadone', 'Amphet', 'Tramad',
       'Hydromorphone', 'Morphine_(Not_Heroin)', 'Xylazine', 'Gabapentin',
       'Opiate_NOS', 'Heroin/Morph/Codeine', 'Other_Opioid', 'Any_Opioid'],
      dtype='object')

In [42]:
df.columns = df.columns.str.strip().str.replace(" ", "_")

print(df.columns)

if 'Date_of_Death' in df.columns:
    df['Date_of_Death'] = pd.to_datetime(df['Date_of_Death'])
elif 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'])
elif 'DateofDeath' in df.columns:
    df['DateofDeath'] = pd.to_datetime(df['DateofDeath'])

print("Date column converted successfully")

Index(['Date_of_death', 'Age', 'Sex', 'Race', 'Residence_City',
       'Residence_County', 'Residence_State', 'Injury_City', 'Injury_County',
       'Injury_State', 'Injury_Place', 'Description_of_Injury', 'Location',
       'Location_if_Other', 'Cause_of_Death', 'Manner_of_Death',
       'Other_Significant_Conditions', 'Heroin', 'Cocaine', 'Fentanyl',
       'Fentanyl_Analogue', 'Oxycodone', 'Oxymorphone', 'Ethanol',
       'Hydrocodone', 'Benzodiazepine', 'Methadone', 'Amphet', 'Tramad',
       'Hydromorphone', 'Morphine_(Not_Heroin)', 'Xylazine', 'Gabapentin',
       'Opiate_NOS', 'Heroin/Morph/Codeine', 'Other_Opioid', 'Any_Opioid'],
      dtype='object')
Date column converted successfully

In [46]:
# Clean column names
df.columns = df.columns.str.strip().str.replace(" ", "_")

# Convert date column
df['Date_of_death'] = pd.to_datetime(df['Date_of_death'])

# Create year column
df['Year'] = df['Date_of_death'].dt.year

In [47]:
df[['Date_of_death', 'Year']].head()

  Date_of_death  Year
0    2023-02-01  2023
1    2023-04-02  2023
2    2022-01-03  2022
3    2023-06-03  2023
4    2023-06-07  2023

In [63]:
df.rename(columns={'Date_of_death': 'Date'}, inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year

# Create Derived Columns

Extract Year from Date:

In [96]:
df.columns = df.columns.str.strip().str.replace(" ", "_").str.lower()

print(df.columns)

Index(['date', 'age', 'sex', 'race', 'residence_city', 'residence_county',
       'residence_state', 'injury_city', 'injury_county', 'injury_state',
       'injury_place', 'description_of_injury', 'location',
       'location_if_other', 'cause_of_death', 'manner_of_death',
       'other_significant_conditions', 'heroin', 'cocaine', 'fentanyl',
       'fentanyl_analogue', 'oxycodone', 'oxymorphone', 'ethanol',
       'hydrocodone', 'benzodiazepine', 'methadone', 'amphet', 'tramad',
       'hydromorphone', 'morphine_(not_heroin)', 'xylazine', 'gabapentin',
       'opiate_nos', 'heroin/morph/codeine', 'other_opioid', 'any_opioid',
       'year'],
      dtype='object')